CREATE TABLE dictionary_words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    source VARCHAR NOT NULL,
    word VARCHAR NOT NULL,
    lexical_entry CLOB NULL,
    status VARCHAR(16) DEFAULT 'CREATED' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT PK_dictionary_words_id PRIMARY KEY (id),
    CONSTRAINT UQ_dictionary_words_source_word UNIQUE (source, word),
    CONSTRAINT status_check CHECK (status IN ('CREATED', 'SCRAPING', 'SCRAPED'))
);