CREATE TABLE dictionary_words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR NOT NULL,
    word VARCHAR NOT NULL,
    lexical_entry TEXT NULL,
    status VARCHAR(16) DEFAULT 'CREATED' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NULL,
    CONSTRAINT UQ_dictionary_words_source_word UNIQUE (source, word),
    CONSTRAINT status_check CHECK (status IN ('CREATED', 'SCRAPING', 'SCRAPED', 'FAILED', 'NOT_FOUND'))
);